version: "3.7"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - drone-ci_overlay
    volumes:
      - ./domain.template:/etc/nginx/conf.d/mysite.template
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 180s
    environment:
      - NGINX_HOST=ikatoo.com.br
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

networks:
  drone-ci_overlay:
    - external
